name: Deploy Hugo Site to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.145.0
      HUGO_ENVIRONMENT: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Build Hugo Site
        run: |
          hugo --gc --minify --baseURL "https://${{ secrets.VPS_DOMAIN }}/"
          touch public/.nojekyll

      - name: Deploy to VPS via rsync
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          rsync -avz --delete -e "ssh -p ${{ secrets.VPS_SSH_PORT }} -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519" public/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/lisenapati/
